<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by Oracle SCA Test Modeler version 1.0 at [12/2/09 8:09 PM]. -->
<compositeTest compositeDN="bpel-106-FaultHandling" xmlns="http://xmlns.oracle.com/sca/2006/test">
  <about>Test the fault throw out of the process boundary</about>
  <initiate serviceName="syncfaulthandling_client_ep" operation="process" isAsync="false" delay="PT0S">
    <message>
      <part partName="payload">
        <content>
          <process xmlns="http://example.com/bpel_106_FaultHandling/SyncFaultHandling">
            <input>some input</input>
          </process>
        </content>
      </part>
    </message>
  </initiate>
  <wireActions wireSource="syncfaulthandling_client_ep" operation="process">
    <assert comparisonMethod="string">
      <description>test of fault bubble with summary</description>
      <expected>
        <location key="fault" faultName="client:anotherBusinessFault" partName="payload" xpath="/client:faultElement/client:summary" xmlns:client="http://example.com/bpel_106_FaultHandling/SyncFaultHandling" xmlns:syn="http://example.com/bpel_106_FaultHandling/SyncFaultHandling"/>
        <simple>Fault happened: some input</simple>
      </expected>
    </assert>
  </wireActions>
</compositeTest>
